vim.keymap.set("n", "<leader>ff", "<cmd>GFiles<cr>")
vim.keymap.set("n", "<leader>fa", "<cmd>Files<cr>")
vim.keymap.set("n", "<leader>fb", "<cmd>Buffers<cr>")
vim.keymap.set("n", "<leader>fg", "<cmd>Rg<cr>")
vim.keymap.set("n", "<leader>fc", "<cmd>Commands<cr>")
vim.keymap.set("n", "<leader>fm", "<cmd>Maps<cr>")
